from app.services.matching.interfaces import Technology, TechnologyCatalogInterface

TECHNOLOGY_CATALOG: tuple[Technology, ...] = (
    Technology("C#", "linguagens", ("c#", "csharp", "c sharp")),
    Technology(".NET", "backend", (".net", "dotnet", "dot net")),
    Technology("JavaScript", "linguagens", ("javascript", "js")),
    Technology("TypeScript", "linguagens", ("typescript", "ts")),
    Technology("Python", "linguagens", ("python",)),
    Technology("PHP", "linguagens", ("php",)),
    Technology("Java", "linguagens", ("java",)),
    Technology("Node.js", "backend", ("node.js", "nodejs", "node js")),
    Technology(
        "Express.js",
        "backend",
        ("express.js", "expressjs", "express", "node express", "node.js & express"),
    ),
    Technology("NestJS", "backend", ("nestjs", "nest.js", "nest js")),
    Technology("FastAPI", "backend", ("fastapi",)),
    Technology("Flask", "backend", ("flask",)),
    Technology("Django", "backend", ("django",)),
    Technology("Django REST Framework", "backend", ("django rest framework", "drf")),
    Technology("Spring Boot", "backend", ("spring boot", "springboot")),
    Technology("Spring", "backend", ("spring framework", "spring")),
    Technology("MVC", "backend", ("mvc", "model view controller")),
    Technology("Laravel", "backend", ("laravel",)),
    Technology("Symfony", "backend", ("symfony",)),
    Technology("ASP.NET Core", "backend", ("asp.net core", "aspnet core", "asp.net")),
    Technology("Next.js", "frontend", ("next.js", "nextjs", "next js")),
    Technology("React", "frontend", ("react",)),
    Technology("Vue", "frontend", ("vue.js", "vuejs", "vue 3", "vue")),
    Technology("Nuxt", "frontend", ("nuxt.js", "nuxtjs", "nuxt")),
    Technology("Angular Material", "frontend", ("angular material",)),
    Technology("Angular", "frontend", ("angular",)),
    Technology("NgRx", "frontend", ("ngrx",)),
    Technology("Signals", "frontend", ("signals",)),
    Technology("Tailwind CSS", "frontend", ("tailwind css", "tailwind")),
    Technology("Bootstrap", "frontend", ("bootstrap",)),
    Technology("shadcn/ui", "frontend", ("shadcn/ui", "shadcn ui", "shadcn")),
    Technology("Radix UI", "frontend", ("radix ui", "radix")),
    Technology("HTML", "frontend", ("html5", "html")),
    Technology("CSS", "frontend", ("css3", "css")),
    Technology("UI/UX", "ferramentas", ("ui/ux", "ui ux")),
    Technology("MongoDB", "bancos_data", ("mongodb",)),
    Technology("DynamoDB", "bancos_data", ("dynamodb",)),
    Technology("PostgreSQL", "bancos_data", ("postgresql", "postgres")),
    Technology("MySQL", "bancos_data", ("mysql",)),
    Technology("SQLite", "bancos_data", ("sqlite",)),
    Technology("Redis", "bancos_data", ("redis",)),
    Technology("MariaDB", "bancos_data", ("mariadb", "maria db")),
    Technology("Prisma", "bancos_data", ("prisma",)),
    Technology("SQLAlchemy", "bancos_data", ("sqlalchemy",)),
    Technology("Eloquent", "bancos_data", ("eloquent",)),
    Technology("Entity Framework", "bancos_data", ("entity framework",)),
    Technology("Docker", "devops", ("docker",)),
    Technology("Docker Compose", "devops", ("docker compose", "docker-compose")),
    Technology("Kubernetes", "devops", ("kubernetes", "k8s")),
    Technology("CI/CD", "devops", ("ci/cd", "ci cd", "continuous integration")),
    Technology("GitHub Actions", "devops", ("github actions",)),
    Technology("Terraform", "devops", ("terraform",)),
    Technology("AWS-SDK", "cloud", ("aws-sdk", "aws sdk")),
    Technology("AWS", "cloud", ("aws",)),
    Technology("Azure", "cloud", ("azure",)),
    Technology("GCP", "cloud", ("gcp", "google cloud")),
    Technology("Vercel", "cloud", ("vercel",)),
    Technology("Netlify", "cloud", ("netlify",)),
    Technology("Railway", "cloud", ("railway",)),
    Technology("Render", "cloud", ("render.com", "render")),
    Technology("Jest", "testes", ("jest",)),
    Technology("Vitest", "testes", ("vitest",)),
    Technology("Pytest", "testes", ("pytest",)),
    Technology("JUnit", "testes", ("junit",)),
    Technology("PHPUnit", "testes", ("phpunit",)),
    Technology("Cypress", "testes", ("cypress",)),
    Technology("Playwright", "testes", ("playwright",)),
    Technology("Selenium", "testes", ("selenium",)),
    Technology("E2E", "testes", ("e2e", "end to end")),
    Technology("Mocha", "testes", ("mocha",)),
    Technology(
        "testes automatizados", "testes", ("testes automatizados", "automated tests")
    ),
    Technology("Git", "ferramentas", ("git",)),
    Technology("branches", "ferramentas", ("branches", "branching")),
    Technology("pull requests", "ferramentas", ("pull requests", "pull request")),
    Technology("code review", "ferramentas", ("code review", "revisao de codigo")),
    Technology("Figma", "ferramentas", ("figma",)),
    Technology("PostHog", "ferramentas", ("posthog",)),
    Technology("APIs", "backend", ("apis", "api rest", "apis rest", "api")),
    Technology("APIs REST", "backend", ("apis rest", "api rest", "restful api", "rest api", "endpoints rest")),
    Technology("integração de sistemas", "backend", ("integracao de sistemas", "integracoes de sistemas")),
    Technology("tratamento de erros", "backend", ("tratamento de erros", "error handling")),
    Technology("SQL", "bancos_data", ("sql",)),
    Technology("SELECT", "bancos_data", ("select",)),
    Technology("JOIN", "bancos_data", ("join", "joins")),
    Technology("WHERE", "bancos_data", ("where",)),
    Technology("INSERT", "bancos_data", ("insert",)),
    Technology("UPDATE", "bancos_data", ("update",)),
    Technology("DELETE", "bancos_data", ("delete",)),
    Technology("modelagem de banco de dados", "bancos_data", ("modelagem de banco de dados", "modelagem de dados")),
    Technology("testes unitários", "testes", ("testes unitarios", "unit tests")),
    Technology("testes de integração", "testes", ("testes de integracao", "integration tests")),
    Technology("metodologias ágeis", "processos", ("metodologias ageis", "scrum", "kanban")),
    Technology("inglês técnico", "languages", ("ingles tecnico", "technical english", "leitura de docs", "leitura de documentacao", "ingles para leitura tecnica")),
    Technology("LLMs", "ia", ("llms", "large language models")),
    Technology("APIs de IA", "ia", ("apis de ia", "api de ia", "ai apis")),
    Technology("OpenAI API", "ia", ("openai api", "api da openai")),
    Technology("Gemini API", "ia", ("gemini api", "api do gemini")),
    Technology("RAG", "ia", ("rag", "retrieval augmented generation")),
    Technology("Embeddings", "ia", ("embeddings", "embedding")),
    Technology("Vector DB", "ia", ("vector database", "banco vetorial", "pgvector", "pinecone", "qdrant", "weaviate", "chroma")),
    Technology("Prompt Engineering", "ia", ("prompt engineering", "engenharia de prompt")),
    Technology(
        "microsserviços",
        "backend",
        ("microsservicos", "microservicos", "microservices"),
    ),
    Technology("arquitetura distribuída", "backend", ("arquitetura distribuida",)),
    Technology("design system", "frontend", ("design system", "design systems")),
    Technology("design tokens", "frontend", ("design tokens", "design token")),
    Technology("acessibilidade", "frontend", ("acessibilidade",)),
    Technology("Flutter", "mobile", ("flutter",)),
    Technology("Dart", "linguagens", ("dart",)),
    Technology("React Native", "mobile", ("react native",)),
    Technology("Kotlin", "linguagens", ("kotlin",)),
    Technology("Swift", "linguagens", ("swift",)),
    Technology("Power BI", "produto", ("power bi", "powerbi")),
    Technology("Pandas", "ia", ("pandas",)),
    Technology("ETL", "arquitetura", ("etl",)),
    Technology("n8n", "automacao", ("n8n",)),
    Technology("Webhooks", "backend", ("webhooks", "webhook")),
    Technology("JWT", "arquitetura", ("jwt",)),
    Technology("OAuth", "arquitetura", ("oauth", "oauth2")),
)

class TechnologyCatalog(TechnologyCatalogInterface):
    """Lookup over the static technology/skill catalog."""

    def find(self, name: str) -> Technology | None:
        return next((item for item in TECHNOLOGY_CATALOG if item.name == name), None)


def find_technology(name: str) -> Technology | None:
    return TechnologyCatalog().find(name)
